<?php
namespace SanctionsList\Resource;

use \SanctionsList\Resource;

class ES_OLD extends Resource
{
    /**
     * Import data in data model.
     *
     * @param \SanctionsList\Model\Sanction
     *
     * @return bool Success?
     */
    public function import(\SanctionsList\Model\Sanction $model)
    {
        // delete old data
        $this->owner->debug('Remove old data...');
        $model->unload(); // just in case
        $model->action('delete')->execute();
        $this->owner->debug('Old data removed');

        // import data
        $this->owner->debug('Importing data...');

        // get XML object
        $xml = $this->stringToXML($this->data);
        $this->owner->debug('Data format is correct XML');

        // parse individuals
        $rows = $xml->xpath('.//ENTITY[@Type = \'P\']');
        $this->owner->debug('Processing '.count($rows).' individuals...');
        $cnt_ind = 0;
        foreach ($rows as $row) {
            $model->set([
                'type'    => 'individual',
                'name'    => (string) $row->NAME[0]->WHOLENAME,
                'country' => (string) null, // no countries in this list
            ]);
            $model->saveAndUnload();
            $cnt_ind++;
        }
        $this->owner->debug('Individuals imported: '.$cnt_ind);

        // parse entities
        $rows = $xml->xpath('.//ENTITY[@Type = \'E\']');
        $this->owner->debug('Processing '.count($rows).' entities...');
        $cnt_ent = 0;
        foreach ($rows as $row) {
            $model->set([
                'type'    => 'entity',
                'name'    => (string) $row->NAME[0]->WHOLENAME,
                'country' => (string) null, // no countries in this list
            ]);
            $model->saveAndUnload();
            $cnt_ent++;
        }
        $this->owner->debug('Entities imported: '.$cnt_ent);

        // done
        $this->owner->debug('Data imported: ' . ($cnt_ind + $cnt_ent) . ' rows');

        return true;
    }
}

/*
<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED BY FSD -->
<WHOLE Date="21/12/2018">

<ENTITY Id="1" Type="P" legal_basis="2018/223 (OJ L43)" reg_date="2018-02-16" pdf_link="http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32018R0223&amp;from=EN" programme="ZWE" remark="(Entity is sanctioned in regime 310/2002 (OJ L50) of programme ZWE, in regime 314/2004 (OJ L55) of programme ZWE)">
    <NAME Id="1" Entity_id="1" legal_basis="2018/223 (OJ L43)" reg_date="2018-02-16" pdf_link="http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32018R0223&amp;from=EN" programme="ZWE">
        <LASTNAME>Mugabe</LASTNAME>
        <FIRSTNAME>Robert</FIRSTNAME>
        <MIDDLENAME>Gabriel</MIDDLENAME>
        <WHOLENAME>Robert Gabriel Mugabe</WHOLENAME>
        <GENDER>M</GENDER>
        <TITLE/>
        <FUNCTION>Former President</FUNCTION>
        <LANGUAGE/>
    </NAME>
    <NAME Id="101396" Entity_id="1" legal_basis="1643/2002 (OJ L247)" reg_date="2002-09-13" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2002:247:0022:0024:EN:PDF" programme="ZWE">
        <LASTNAME>Mugabe</LASTNAME>
        <FIRSTNAME>Robert</FIRSTNAME>
        <MIDDLENAME>Gabriel</MIDDLENAME>
        <WHOLENAME>Robert Gabriel Mugabe</WHOLENAME>
        <GENDER>M</GENDER>
        <TITLE/>
        <FUNCTION>president</FUNCTION>
        <LANGUAGE/>
    </NAME>
    <BIRTH Id="1" Entity_id="1" legal_basis="898/2005 (OJ L153)" reg_date="2005-06-16" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2005:153:0009:0014:EN:PDF" programme="ZWE">
        <DATE>1924-02-21</DATE>
        <PLACE/>
        <COUNTRY/>
    </BIRTH>
    <BIRTH Id="101395" Entity_id="1" legal_basis="1643/2002 (OJ L247)" reg_date="2002-09-13" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2002:247:0022:0024:EN:PDF" programme="ZWE">
        <DATE>1924-02-21</DATE>
        <PLACE>Kutama</PLACE>
        <COUNTRY/>
    </BIRTH>
    <PASSPORT Id="315" Entity_id="1" legal_basis="151/2012 (OJ L49)" reg_date="2012-02-22" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2012:049:0002:0016:EN:PDF" programme="ZWE">
        <NUMBER>AD001095 (passport-National passport) ((passport))</NUMBER>
        <COUNTRY></COUNTRY>
    </PASSPORT>
</ENTITY>

<ENTITY Id="207" Type="E" legal_basis="2018/468 (OJ L79)" reg_date="2018-03-23" pdf_link="http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32018R0468&amp;qid=1521740406834&amp;from=EN" programme="TERR" remark="">
    <NAME Id="327" Entity_id="207" legal_basis="2003/902/EC (OJ L340)" reg_date="2003-12-22" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2003:340:0063:0064:EN:PDF" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Great Islamic Eastern Warriors Front</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE/>
    </NAME>
    <NAME Id="328" Entity_id="207" legal_basis="2004/306/EC (OJ L99)" reg_date="2004-04-02" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:099:0028:0029:EN:PDF" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>IBDA-C</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE/>
    </NAME>
    <NAME Id="450" Entity_id="207" legal_basis="2003/902/EC (OJ L340)" reg_date="2003-12-22" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2003:340:0063:0064:EN:PDF" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Front islamique des combattants du Grand Orient</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>FR</LANGUAGE>
    </NAME>
    <NAME Id="482" Entity_id="207" legal_basis="2003/902/EC (OJ L340)" reg_date="2003-12-22" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2003:340:0063:0064:EN:PDF" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Frente de Guerreros del Gran Oriente Islámico</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>ES</LANGUAGE>
    </NAME>
    <NAME Id="521" Entity_id="207" legal_basis="2003/902/EC (OJ L340)" reg_date="2003-12-22" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2003:340:0063:0064:EN:PDF" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Μέγα Ισλαµικό Μέτωπο των Πολεµιστών της Ανατολής</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>EL</LANGUAGE>
    </NAME>
    <NAME Id="616" Entity_id="207" legal_basis="2003/902/EC (OJ L340)" reg_date="2003-12-22" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2003:340:0063:0064:EN:PDF" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Front der islamischen Kämpfer des Großen Ostens</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>DE</LANGUAGE>
    </NAME>
    <NAME Id="686" Entity_id="207" legal_basis="2003/902/EC (OJ L340)" reg_date="2003-12-22" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2003:340:0063:0064:EN:PDF" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Fronte islamico dei combattenti del grande oriente</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>IT</LANGUAGE>
    </NAME>
    <NAME Id="3725" Entity_id="207" legal_basis="2005/221/CFSP (OJ L69)" reg_date="2005-03-16" pdf_link="http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32005D0221&amp;qid=1410439221593&amp;from=EN" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Fronta islámských bojovníků Velkého východu</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>CS</LANGUAGE>
    </NAME>
    <NAME Id="3726" Entity_id="207" legal_basis="2005/221/CFSP (OJ L69)" reg_date="2005-03-16" pdf_link="http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32005D0221&amp;qid=1410439221593&amp;from=EN" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Suur Islami Idavõitlejate Rinne</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>ET</LANGUAGE>
    </NAME>
    <NAME Id="3727" Entity_id="207" legal_basis="2005/221/CFSP (OJ L69)" reg_date="2005-03-16" pdf_link="http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32005D0221&amp;qid=1410439221593&amp;from=EN" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Lielā Islāma Austrumu cīnītāju fronte</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>LV</LANGUAGE>
    </NAME>
    <NAME Id="3728" Entity_id="207" legal_basis="2005/221/CFSP (OJ L69)" reg_date="2005-03-16" pdf_link="http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32005D0221&amp;qid=1410439221593&amp;from=EN" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Didysis islamo rytų karių frontas</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>LT</LANGUAGE>
    </NAME>
    <NAME Id="3729" Entity_id="207" legal_basis="2005/221/CFSP (OJ L69)" reg_date="2005-03-16" pdf_link="http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32005D0221&amp;qid=1410439221593&amp;from=EN" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Nagy Iszlám Keleti Harci Front</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>HU</LANGUAGE>
    </NAME>
    <NAME Id="3730" Entity_id="207" legal_basis="2005/221/CFSP (OJ L69)" reg_date="2005-03-16" pdf_link="http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32005D0221&amp;qid=1410439221593&amp;from=EN" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Islamski Front Bojowników o Wielki Wschód</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>PL</LANGUAGE>
    </NAME>
    <NAME Id="3731" Entity_id="207" legal_basis="2005/221/CFSP (OJ L69)" reg_date="2005-03-16" pdf_link="http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32005D0221&amp;qid=1410439221593&amp;from=EN" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Islamský front veľkých východných bojovníkov</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>SK</LANGUAGE>
    </NAME>
    <NAME Id="3732" Entity_id="207" legal_basis="2005/221/CFSP (OJ L69)" reg_date="2005-03-16" pdf_link="http://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32005D0221&amp;qid=1410439221593&amp;from=EN" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Fronta islamskih bojevnikov velikega vzhoda</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>SL</LANGUAGE>
    </NAME>
    <NAME Id="4538" Entity_id="207" legal_basis="2005/930/EC (OJ L340)" reg_date="2005-12-23" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2005:340:0064:0066:EN:PDF" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Grande Frente Islâmica Oriental de Combatentes</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>PT</LANGUAGE>
    </NAME>
    <NAME Id="5659" Entity_id="207" legal_basis="2007/445/EC (OJ L169)" reg_date="2007-06-29" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2007:169:0058:0062:EN:PDF" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Фронт на великите ислямски източни воини</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>BG</LANGUAGE>
    </NAME>
    <NAME Id="5660" Entity_id="207" legal_basis="2007/445/EC (OJ L169)" reg_date="2007-06-29" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2007:169:0058:0062:EN:PDF" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>Marele Front Islamic de Est al Războinicilor</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE>RO</LANGUAGE>
    </NAME>
    <NAME Id="6068" Entity_id="207" legal_basis="2007/868/EC (OJ L340)" reg_date="2007-12-20" pdf_link="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2007:340:0100:0103:EN:PDF" programme="TERR">
        <LASTNAME/>
        <FIRSTNAME/>
        <MIDDLENAME/>
        <WHOLENAME>İslami Büyük Doğu Akıncılar Cephesi</WHOLENAME>
        <GENDER/>
        <TITLE/>
        <FUNCTION/>
        <LANGUAGE/>
    </NAME>
</ENTITY>

</WHOLE>

*/
